CREATE TABLE IF NOT EXISTS athlete_profiles (
    clientEmail      TEXT PRIMARY KEY REFERENCES clients(email) ON UPDATE CASCADE ON DELETE CASCADE,
    experience_level TEXT,
    training_focus   TEXT,
    sport            TEXT,
    competition_date TEXT,
    limitations      TEXT NOT NULL DEFAULT '[]',
    private_notes    TEXT,
    updated_at       TEXT NOT NULL DEFAULT (datetime('now')),
    updated_by       TEXT
);

CREATE TABLE IF NOT EXISTS movement_patterns (
    id                    TEXT PRIMARY KEY,
    name                  TEXT NOT NULL UNIQUE,
    label                 TEXT NOT NULL,
    description           TEXT,
    coach_cues            TEXT,
    common_substitutions  TEXT,
    display_order         INTEGER NOT NULL DEFAULT 0
);

INSERT INTO movement_patterns (id, name, label, description, coach_cues, common_substitutions, display_order) VALUES
('mp-01','overhead_press','Overhead Press','Vertical pushing with arm(s) above shoulder height under load','{"right_shoulder":"Landmine press, neutral grip DB press","left_shoulder":"Landmine press, neutral grip DB press","neck":"Avoid barbell behind-neck — use front rack or DB","right_wrist":"Use dumbbells with neutral grip","left_wrist":"Use dumbbells with neutral grip","head":"Postpone until cleared — no overhead loading on concussion protocol"}','Landmine press, Cable shoulder press, DB Z-press, KB press (neutral grip)',1),
('mp-02','horizontal_push','Horizontal Push','Pushing horizontally at chest height — bench press, push-up','{"right_shoulder":"Neutral grip DB, floor press angle","left_shoulder":"Neutral grip DB","right_wrist":"Neutral grip DB, hex DB push-up","left_wrist":"Neutral grip DB, hex DB push-up","right_hand":"Use handles or neutral-grip DB","left_hand":"Use handles or neutral-grip DB","lower_back":"Floor press reduces lumbar arch demand"}','DB bench (neutral grip), Floor press, Cable chest press, Machine press',2),
('mp-03','weight_bearing_hands','Weight Bearing on Hands','Exercises where wrists bear bodyweight load — plank, push-up, handstand','{"right_wrist":"Substitute forearm support — forearm plank, forearm push-up","left_wrist":"Substitute forearm support","right_hand":"Use forearm support or push-up handles","left_hand":"Use forearm support or push-up handles","right_elbow":"Use straight-arm variation or forearm plank","left_elbow":"Use straight-arm variation"}','Forearm plank, Forearm push-up, Dead bug (core sub), TRX row (upper-body sub)',3),
('mp-04','vertical_pull','Vertical Pull','Pulling from overhead — pull-up, lat pulldown','{"right_shoulder":"Neutral grip attachment, reduce range of motion","left_shoulder":"Neutral grip attachment","right_elbow":"Avoid supinated grip — use neutral","left_elbow":"Avoid supinated grip","neck":"Avoid behind-neck pulldown","lower_back":"No kipping — controlled eccentric only"}','Neutral grip lat pulldown, Cable straight-arm pulldown, Band-assisted pull-up, Seated row (shoulder sub)',4),
('mp-05','horizontal_pull','Horizontal Pull','Rowing motions — bent-over row, cable row, machine row','{"right_shoulder":"Neutral grip, limit elbow flare","left_shoulder":"Neutral grip, limit elbow flare","lower_back":"Chest-supported row (DB or machine)","right_wrist":"Use straps and neutral grip attachment","left_wrist":"Use straps and neutral grip"}','Chest-supported DB row, Cable seated row (neutral grip), Machine row, Face pull',5),
('mp-06','bilateral_hinge','Bilateral Hinge','Hip hinge with both legs — deadlift, RDL, good morning','{"lower_back":"Romanian deadlift or trap bar over conventional, reduce ROM","left_hip":"Limit hip flexion — trap bar or hex bar","right_hip":"Limit hip flexion — trap bar or hex bar","left_knee":"Trap bar deadlift, avoid sumo if painful","right_knee":"Trap bar deadlift","neck":"Cue long spine — no chin tuck or jut"}','Trap bar deadlift, Romanian deadlift, Cable pull-through, Good morning (bodyweight)',6),
('mp-07','single_leg_hinge','Single-Leg Hinge','Hip hinge on one leg — single-leg RDL, single-leg deadlift','{"lower_back":"Use wall or TRX support for balance — reduce load","left_hip":"Limit load, avoid on acute flare","right_hip":"Limit load, avoid on acute flare","left_ankle":"Reduce load, use floor touch not full range","right_ankle":"Reduce load"}','Supported SL RDL (TRX or wall), Box hip hinge (bilateral), Single-leg glute bridge',7),
('mp-08','bilateral_squat','Bilateral Squat','Two-leg squatting — back squat, goblet, leg press','{"lower_back":"Goblet squat, box squat, reduce depth, high-bar position","left_knee":"Box squat, leg press (high foot placement), reduce depth","right_knee":"Box squat, leg press (high foot placement)","left_hip":"Reduce depth, wide stance, box squat","right_hip":"Reduce depth, wide stance","left_ankle":"Heel elevation, goblet squat","right_ankle":"Heel elevation","neck":"Goblet squat or safety bar to avoid bar contact"}','Goblet squat, Box squat, Leg press, Safety bar squat, Belt squat',8),
('mp-09','single_leg_squat','Single-Leg Squat / Lunge','Unilateral lower body — split squat, lunge, step-up, pistol','{"left_knee":"Box step-up (low box), reverse lunge over forward lunge, reduce load","right_knee":"Box step-up, reverse lunge","lower_back":"Goblet hold, reduce forward lean","left_hip":"Limit hip flexion angle, elevated rear foot RFESS","right_hip":"Limit angle, elevated rear foot","left_ankle":"Heel elevation under front foot","right_ankle":"Heel elevation"}','Box step-up, Reverse lunge, TRX-assisted split squat, Elevated rear foot split squat',9),
('mp-10','hip_thrust','Hip Thrust / Bridge','Hip extension without axial spinal load — hip thrust, glute bridge, cable pull-through','{"lower_back":"Excellent substitute for other lower-back loading — preferred","left_knee":"Maintain 90° or reduce foot elevation","right_knee":"Maintain 90° or reduce foot elevation","neck":"Chin tucked — avoid hyperextension at lockout"}','Banded hip thrust, Single-leg glute bridge, Cable pull-through, Frog pump',10),
('mp-11','anti_rotation','Anti-Rotation','Resisting rotational force — Pallof press, single-arm work, landmine anti-rotation','{"lower_back":"Reduce resistance, widen stance for stability","right_shoulder":"Use lower anchor point, lighter load","left_shoulder":"Lower anchor point, lighter load","neck":"Neutral head position throughout"}','Banded Pallof press, Half-kneeling chop (light), Dead bug, Single-arm farmer hold',11),
('mp-12','anti_extension','Anti-Extension','Resisting spinal extension — plank, ab wheel, hollow body','{"lower_back":"Elevate hands, reduce lever arm (bent-knee plank)","right_shoulder":"Forearm plank — avoid straight-arm plank","left_shoulder":"Forearm plank","right_wrist":"Forearm plank or dead bug","left_wrist":"Forearm plank or dead bug"}','Elevated plank, Dead bug, Hollow body hold, TRX fallout (regressed)',12),
('mp-13','anti_lateral_flexion','Anti-Lateral Flexion','Resisting side-bending — side plank, suitcase carry, Copenhagen plank','{"lower_back":"Forearm side plank, reduce lever arm","left_shoulder":"Forearm side plank — suitcase carry instead","right_shoulder":"Forearm side plank — suitcase carry","left_hip":"Avoid Copenhagen plank on acute flare","right_hip":"Avoid Copenhagen plank on acute flare"}','Forearm side plank, Suitcase carry, DB offset hold',13),
('mp-14','spinal_rotation','Spinal Rotation','Active rotation — woodchop, cable rotation, med ball throw','{"lower_back":"Limit lumbar contribution, focus on thoracic — reduce load significantly","right_shoulder":"Lower anchor point, neutral grip","left_shoulder":"Lower anchor point","neck":"Maintain neutral — do not follow movement with head","head":"Avoid on concussion protocol — no rotational loading"}','Half-kneeling cable chop (light, controlled), Seated thoracic rotation (no load)',14),
('mp-15','spinal_flexion','Spinal Flexion','Active spinal flexion — crunch, sit-up, GHD sit-up','{"lower_back":"Avoid on disc issues — substitute dead bug or hollow body hold","neck":"Hands behind head without pulling — or avoid entirely","head":"Avoid entirely on concussion protocol — postpone until cleared"}','Dead bug, Hollow body hold, TRX fallout, McGill curl-up (minimal flexion)',15),
('mp-16','loaded_carry','Loaded Carry','Carrying load while walking — farmer, yoke, waiter walk','{"lower_back":"Lighter load, shorter distance, belt if needed","right_shoulder":"Suitcase carry left side only, or trap bar farmer carry","left_shoulder":"Suitcase carry right side only, or trap bar","right_hand":"Use wrist straps","left_hand":"Use wrist straps","right_wrist":"Use straps","left_wrist":"Use straps","neck":"Avoid yoke carry — use trap bar or DBs"}','Trap bar farmer carry, Suitcase carry (one side), Goblet carry, Sandbag carry',16),
('mp-17','impact_plyometric','Impact / Plyometric','Ground-contact exercises — running, jumping, bounding, box jump','{"left_knee":"Land on two feet, reduce box height, step-down instead of jump-down","right_knee":"Land on two feet, reduce height, step-down","left_ankle":"Avoid single-leg impact, reduce height, pool running","right_ankle":"Pool running, bike sprint alternative","lower_back":"Reduce ground impact force — pool running or bike sprint","head":"No impact activity until fully cleared from concussion protocol"}','Pool running, Stationary bike sprint, Step-up (vs jump), Slow tempo box step',17),
('mp-18','olympic_ballistic','Olympic / Ballistic','High-velocity full-body movements — clean, snatch, KB swing, med ball slam','{"lower_back":"Avoid on acute flare — substitute KB deadlift or sumo pull","right_shoulder":"Avoid overhead catch — hang pull instead of full clean","left_shoulder":"Avoid overhead catch — hang pull","right_wrist":"Avoid rack position — KB swing or sumo pull instead","left_wrist":"KB swing or sumo pull","head":"Avoid entirely on concussion protocol"}','KB swing, Sumo pull, DB hang pull, Med ball deadlift slam (no overhead)',18);
